runtime: php55
api_version: 1


handlers:
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg|css|svg))$
  static_files: \1
  upload: .+\.(gif|png|jpg|css|svg)$
  application_readable: true

# Serve php scripts.
- url: /(.+\.php)$
  script: \1

- url: /|/.*|/index.html|home.html
  script: Index.php

